import type { FastifyPluginAsync } from 'fastify';
// Importing a module registers its entity types (for links, tags, search) and its jobs.
import './workspaces/service';
import './documents/service';
import './finance/accounts';
import './finance/transactions';
import './finance/installments';
import './finance/debts';
import './finance/budgets';
import './finance/goals';
import './finance/jobs';
import './finance/interest';
import './life/people';
import './life/tasks';
import './life/events';
import './life/goals';
import './life/notes';
import './life/jobs';
import './business/organizations';
import './business/pipeline';
import './business/projects';
import './business/jobs';
import './career/applications';
import './career/profile';
import './career/jobs';
import './insights/assets';
import './insights/reviews';
import './insights/scenarios';
import './insights/jobs';
import './automation/engine';
import '../jobs/core-jobs';
import { aiRoutes } from './ai/routes';
import { automationRoutes } from './automation/routes';
import { businessRoutes } from './business/routes';
import { careerRoutes } from './career/routes';
import { financeRoutes } from './finance/routes';
import { insightsRoutes } from './insights/routes';
import { lifeRoutes } from './life/routes';

/** Route plugins of feature modules (finance, tasks, CRM, …). */
export const moduleRoutes: FastifyPluginAsync[] = [financeRoutes, lifeRoutes, businessRoutes, careerRoutes, insightsRoutes, automationRoutes, aiRoutes];
